name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and start virtual environment
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-dev -y
        sudo apt-get upgrade -y
        sudo pip3 install virtualenv
        git clone https://github.com/Mohanraj209/new_chatapp.git
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-dev -y
        sudo apt-get upgrade -y
        cd new_chatapp/
        virtualenv -p /usr/bin/python3 venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        pip3 install gunicorn
        sudo apt-get install python3-dev default-libmysqlclient-dev build-essential
        pip3 install mysqlclient
        cd fundoo
        python3 -m pip install -U channels
    - name: Run Tests
      run: |
        python3 manage.py makemigrations 
        python3 manage.py migrate
        sudo systemctl daemon-reload
        sudo systemctl start gunicorn
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          . 
          !venv/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'chatapp1818'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1E75A5462D2B4DF284814F87F1F4E67A }}
