name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and start virtual environment
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-dev -y
        sudo apt-get upgrade -y
        sudo pip3 install virtualenv
    - name: Install Dependencies
      run: |
        pwd
        ls
        cd new_chatapp/
        virtualenv -p /usr/bin/python3 venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        pip3 install gunicorn
        sudo apt-get install python3-dev default-libmysqlclient-dev build-essential
        pip3 install mysqlclient
        cd fundoo
        python -m pip install -U channels
    - name: Run Tests
      run: |
        cd /home/docker-vm/mohan/new_chatapp/fundoo
        python manage.py makemigrations 
        python manage.py migrate
        sudo systemctl daemon-reload
        sudo systemctl start gunicorn
    
